jobs:
  build:
    machine:
      image: circleci/classic:edge
      working_directory: ~/
      steps:
        - checkout
        - run:
            name: Run build script
            command: ./build
