version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:edge
    parallelism: 1

    steps:
      - checkout
      - run:
          name: Run build script
          command: ./build
          working_directory: ~/

workflows:
  version: 2
    test:
      jobs:
        - build
