version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    parallelism: 2
    branches:
      ignore:

    steps:
      - checkout

      - run: |
          if [[ ! -e ~/deps/bats_v0.4.0.tar.gz ]]; then mkdir -p ~/deps; \
          curl -sSL -o ~/deps/bats_v0.4.0.tar.gz \
          https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz; fi && \
          tar -xf ~/deps/bats_v0.4.0.tar.gz && sudo bats-0.4.0/install.sh \
          /usr/local

#      - save_cache:
#          key: dependencies
#          paths: ~/deps/

      - run:
          name: Run build script
          command: ./build

      - run:
          name: Run tests
          command: ./build test
          environment:
            - files: "versions/**/options"
