version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    parallelism: 2
    branches:
      ignore:

    steps:
      - checkout

      - run: |
          if [[ ! -e ~/deps/bats_v0.4.0.tar.gz ]]; then mkdir -p ~/deps; \
          curl -sSL -o ~/deps/bats_v0.4.0.tar.gz \
          https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz; fi && \
          tar -xf ~/deps/bats_v0.4.0.tar.gz && sudo bats-0.4.0/install.sh \
          /usr/local

      - run: |
          if [[ ! -e ~/deps/manifest-tool-linux-amd64 ]]; then mkdir -p ~/deps; \
          curl -sSL -o ~/deps/manifest-tool-linux-amd64 \
          https://github.com/estesp/manifest-tool/releases/download/v0.6.0/manifest-tool-linux-amd64; fi && \
          chmod +x ~/deps/manifest-tool-linux-amd64

      - run:
          name: Run build script
          command: ./build

      - run:
          name: Run tests
          command: ./build test
          environment:
            - files: "versions/**/options"

      - run:
          name: Clear Docker images
          command: /bin/bash -c 'docker rmi troyfontaine/armhf-alpinelinux:3.6 troyfontaine/armhf-alpinelinux:latest troyfontaine/armhf-alpinelinux:3.5  troyfontaine/armhf-alpinelinux:edge troyfontaine/x86_64-alpinelinux:3.6 troyfontaine/x86_64-alpinelinux:latest troyfontaine/x86_64-alpinelinux:3.5 troyfontaine/x86_64-alpinelinux:edge'

      - run:
          name: Build Release images
          command: ./build release

      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io

      - run:
          name: Push ARM images to Dockerhub
          command: docker push troyfontaine/armhf_min-alpinelinux

      - run:
          name: Push x86_64 images to Dockerhub
          command: docker push troyfontaine/x86_64-alpinelinux

      - run:
          name: Create multi-architecture image
          command: manifest-tool-linux-amd64 --username $DOCKER_USER --password $DOCKER_PASSWORD push from-spec ~/alpine-multi.yml
