version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:edge

    parallelism: 2
    branches:
      ignore:

    steps:
      - checkout

      - run:
          name: Run build script
          command: ./build
