version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:edge
    parallelism: 1

    steps:
      - run: echo 127.0.0.1 circlehost | tee -a /etc/hosts
      - run: command: ls
      - run:
          name: Run build script
          command: ./build
          working_directory: ~/
